### PR TITLE
Added support for exact match with generics. Fixed some minor issues

### LINKED ISSUE #26: Deserialize generic types

### PR DESCRIPTION
**Pull request by pikinier20**
Fixes #26 

Fixed minor bugs:
-Pretty printing type variables,
-Filtering projection to Any?
-Ignoring type variable names

### CODE REVIEW

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala [hunk 1]
```diff
@@ -1,12 +1,6 @@
 package org.virtuslab.inkuire.engine.cli.service
 
-import org.virtuslab.inkuire.engine.model.Signature
-import org.virtuslab.inkuire.engine.model.ExternalSignature
-import org.virtuslab.inkuire.engine.model.ConcreteType
-import org.virtuslab.inkuire.engine.model.GenericType
-import org.virtuslab.inkuire.engine.model.Type
-import org.virtuslab.inkuire.engine.model.FunctionType
-import org.virtuslab.inkuire.engine.model.TypeVariable
+import org.virtuslab.inkuire.engine.model.{ConcreteType, ExternalSignature, FunctionType, GenericType, Signature, SignatureContext, Type, TypeVariable}
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:3]: `import org.virtuslab.inkuire.engine.model._`

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala [hunk 2]
```diff
@@ -19,7 +13,17 @@ class KotlinExternalSignaturePrettifier {
   }
 
   private def prettifySignature(sgn: Signature): String = {
-    s"${prettifyReceiver(sgn.receiver)}(${prettifyArgs(sgn.arguments)}) -> ${prettifyType(sgn.result)}"
+    s"${prettifyGenerics(sgn.context)}${prettifyReceiver(sgn.receiver)}(${prettifyArgs(sgn.arguments)}) -> ${prettifyType(sgn.result)}"
+  }
+
+  private def prettifyGenerics(context: SignatureContext): String = {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:19]: `prettifyTypeParams`?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala [hunk 3]
```diff
@@ -19,7 +13,17 @@ class KotlinExternalSignaturePrettifier {
...
+    if(context.vars.isEmpty) ""
+    else {
+      val consSeq = context.constraints.flatMap{
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:22]: `constraints`?
I mean the name. Appending type to variable name feels kinds C#-like.

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala [hunk 4]
```diff
@@ -19,7 +13,17 @@ class KotlinExternalSignaturePrettifier {
...
+        case (key,value) => value.map(v => s"$key: ${prettifyType(v)}")
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]: There can be multiple upper-bounds in Kotlin, right?(genuinely not sure)
If so, this will not really work. it will produce `<T: A, T: B, T: C ... >`

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala [hunk 5]
```diff
@@ -18,12 +18,36 @@ case class InkuireDb(
 object InkuireDb {
   implicit def listAsScala[T](list: java.util.List[T]): Iterable[T] = list.asScala
 
-  @tailrec
-  private def parseBound(b: SBound): String = {
+  private def parseProjection(p: SProjection): Type = p match {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala:21]: not a fan of naming those functions `parse...` maybe `translate...`?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala [hunk 6]
```diff
@@ -18,12 +18,36 @@ case class InkuireDb(
 object InkuireDb {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala:18]: since this object is starting to grow, maybe it would be a good idea to create a service for this logic? Sth like `DokkaModelTranslationService`?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/Signature.scala [hunk 7]
```diff
@@ -10,7 +10,14 @@ case class Signature(
 case class SignatureContext(
   vars: Set[String],
   constraints: Map[String, Seq[Type]]
-)
+) {
+  override def equals(obj: Any): Boolean = obj match {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/Signature.scala:14]: As discussed, not sure about this equals.
IMHO it should be separate from model, because it is only valid for exact match(most likely). Maybe we should consider making a separate type class for checking equality? Or consider using `cats.kernel.Eq`?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/Type.scala [hunk 8]
```diff
@@ -60,6 +60,11 @@ case class TypeVariable(
   override def asConcrete: Type = this.transformInto[ConcreteType]
 
   override def ? : Type = this.modify(_.nullable).setTo(true)
+
+  override def equals(obj: Any): Boolean = obj match {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/Type.scala:64]: Same as with `SignatureContext`

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala [hunk 9]
```diff
@@ -18,12 +18,36 @@ case class InkuireDb(
...
 
-  @tailrec
-  private def parseBound(b: SBound): String = {
+  private def parseProjection(p: SProjection): Type = p match {
+    case _: SStar => StarProjection
+    case s: SVariance => parseBound(s.getInner)
+    case b: SBound => parseBound(b)
+  }
+
+  private def parseGenerics(f: SDFunction): SignatureContext = {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala:27]: `...TypeParams` or `...TypeBounds`?

**Comment by KacperFKorban** [comment]
I feel like the commit message isn't really in sync with the changes and PR description?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala (hunk 4 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]: and thats how you represent it in Kotlin, but multiple bounds are supported only in "where" clause.

Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]:
```Kotlin
fun <NI> addSortedSection(name: String, namedIdentifiables: List<NI>, category: Category)
        where NI : Named, NI : Identifiable
```
It's legit signature, we don't support where, so it goes to < >

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala (hunk 6 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/model/InkuireDb.scala:18]: That's actually a good point, I've thought about it

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala (hunk 4 above)
Comment (KacperFKorban) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]: `where` clause is supported in parser, so maybe for now we should display every bound in `where` and create a task for a special case with a type variable with exactly one bound?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala (hunk 3 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:22]: cmon its just helper variable ^^

Comment (KacperFKorban) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:22]: Ok, but I feel like reading our C# connector code. Stuff like `SeqOfParametrDynamiczny`

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala (hunk 4 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]: actually when we move all constraints to 'where' it is always a correct signature, so maybe just implement it that way and let it be

Comment (KacperFKorban) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/cli/service/KotlinExternalSignaturePrettifier.scala:23]: LGTM

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/DefaultDokkaModelTranslationService.scala [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+object DefaultDokkaModelTranslationService extends DokkaModelTranslationService {
+  implicit def listAsScala[T](list: java.util.List[T]): Iterable[T] = list.asScala
+
+  private def parseProjection(p: SProjection): Type = p match {
+    case _: SStar => StarProjection
+    case s: SVariance => parseBound(s.getInner)
+    case b: SBound => parseBound(b)
+  }
+
+  private def parseGenerics(f: SDFunction): SignatureContext = {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/DefaultDokkaModelTranslationService.scala:19]: `translateTypeParams` or `translateTypeBounds`?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/DefaultDokkaModelTranslationService.scala [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+import org.virtuslab.inkuire.engine.model._
+import org.virtuslab.inkuire.model._
+import org.virtuslab.inkuire.engine.model.Type._
+
+import scala.jdk.CollectionConverters._
+
+object DefaultDokkaModelTranslationService extends DokkaModelTranslationService {
+  implicit def listAsScala[T](list: java.util.List[T]): Iterable[T] = list.asScala
+
+  private def parseProjection(p: SProjection): Type = p match {
```
Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/DefaultDokkaModelTranslationService.scala:13]: `translateProjection`?
