### PR TITLE
Incorrect match bugfix

### LINKED ISSUE #85: Inocrrent matches
`<C> C.(() -> C) -> C`
`<K, V> Map<K, V>.(K) -> V`

### PR DESCRIPTION
**Pull request by pikinier20**
closes #85

### CODE REVIEW

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala [hunk 1]
```diff
@@ -93,14 +93,60 @@ class FluffMatchService(val inkuireDb: InkuireDb) extends BaseMatchService with
...
     //TODO can be done better
+    //<C> C.(() -> C) -> C
+    //<T> Sequence<T>.(T) -> Sequence<T>
+
+    //<C> C.(C) -> C
+    //<T> Sequence<T>.(T) -> Sequence<T>
+
+    //<C> C.(Sequence<C>) -> C
+    //<T> Sequence<T>.(T) -> Sequence<T>
+
```
Comment (pikinier20) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala:104]: XD

Comment (BarkingBad) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala:104]: Why won't u delete it?

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala [hunk 2]
```diff
@@ -93,14 +93,60 @@ class FluffMatchService(val inkuireDb: InkuireDb) extends BaseMatchService with
...
         .forall {
           case a :: b :: Nil => a.dri == b.dri
           case _             => true
         }
+    } && TypeVariablesGraph(bindings).checkCyclicDependency
+  }
+}
+
+case class TypeVariablesGraph(dependencyGraph: Map[DRI, Seq[DRI]]) {
+  def checkCyclicDependency: Boolean = {
```
Comment (BarkingBad) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala:117]: Name is not intuitive. I would rename it to `isCyclicDependency`

Comment (KacperFKorban) [inline inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala:117]: I think that You're overthinking this DFS. For one thing, I am fairly certain that the Boolean result value is unused. Plus I feel like using Either here isn't adding that much. Using monads is a good choice when You want to utilise the cool instances `cats` offer, but I think that it is a bit overkill here.
I am fairly certain that start isn't needed here, because ATM we are only finding cyclic dependency if there is a cyclic dependency to the start, which isn't always the case. There is a cyclic dependency every time we try visiting a visited node.

Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala:117]: I knew that using Either here is overkill but I needed to return information about new visited nodes or detected cycle and my mind was total blank. I had there `start` argument because this graph is directed so you cannot check visited like that, yesterday I thought that I need to make it `n` times to check it, but actually you can remember stack of recursion and check if your node is not already on stack. I'm gonna make fixes right now.

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala [hunk 3]
```diff
@@ -93,14 +93,60 @@ class FluffMatchService(val inkuireDb: InkuireDb) extends BaseMatchService with
...
+        loop(v, v, Set(v)) match {
+          case Left(_)  => true
+          case Right(_) => false
+      }
+    )
+  }
+}
+
+object TypeVariablesGraph {
+  def apply(variableBindings: VariableBindings): TypeVariablesGraph = {
```
[the remark this answers is not in the document]
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala]: changed

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala (hunk 2 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala]: renamed to `hasCyclicDependency`

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala (hunk 1 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala]: deleted XD

File: inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala (hunk 2 above)
Comment (pikinier20) [reply inkuire-engine/src/main/scala/org/virtuslab/inkuire/engine/service/FluffMatchService.scala]: Changed return type to Option (Some contains visited nodes, None informs that there's cycle)

**Review by KacperFKorban — APPROVED** [review]
